### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by sunzhcas** [z1069614715/objectdetection_script#1]
Transferred 348/349 items
  0%|                                                                                          | 0/504 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "yolov5_heatmap.py", line 117, in <module>
    model(r'E:\test\envyolo5\yolov5C3\datasets\00194.jpg', 'result')
  File "yolov5_heatmap.py", line 81, in __call__
    score.backward(retain_graph=True)
  File "E:\test\envyolo5\lib\site-packages\torch\tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "E:\test\envyolo5\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 3, 20, 20, 7]], which is output 0 of SigmoidBackward, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

请问UP这个怎么破，谢谢

**Comment by z1069614715** [comment]
你这个是yolov5的什么版本？

**Comment by sunzhcas** [comment]
yolov5 v6.2

**Comment by z1069614715** [comment]
注意事项已经写了 我是在v7.0编写和测试的 之前的版本有可能跑不通

**Comment by sunzhcas** [comment]
哦哦，好的，谢谢UP，我再试试。
