### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by 123678916** [z1069614715/objectdetection_script#17]
https://github.com/z1069614715/objectdetection_script/blob/master/yolo-improve/yolov5-DecoupledHead.py
Line 70 "if m is Detect:" should be "if isinstance(m, Detect)".
Similarly for Line 76

**Comment by z1069614715** [comment]
如果这是一个bug的话 你得提交给yolov5的官方了 因为yolov5也是这么写的

**Comment by z1069614715** [comment]
在我看来 如果这个是个bug 代码是跑不通的

**Comment by 123678916** [comment]
代码不会报错，但是不会使用定制的初始化方式，而是用随机初始化。

**Comment by z1069614715** [comment]
嗯，你说的是初始化部分哈，确实是的，因为Detect是一个实例化的类了，需要使用isinstance判断，感谢提醒

**Comment by z1069614715** [comment]
已经更新
