### ISSUE TITLE
如何加入到v7内使用？

### ISSUE THREAD

**Issue by Zzzz1zzz** [z1069614715/objectdetection_script#21]
是将整个Biformer.py加入到v7内？ 还是将某一段加入到common.py内 yolo.py里注册？

**Comment by z1069614715** [comment]
https://www.bilibili.com/video/BV1X24y157Et/

**Comment by Zzzz1zzz** [comment]
好的，多谢UP。我先看视频研究一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "z1069614715/objectdetection_script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 上午8:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [z1069614715/objectdetection_script] 如何加入到v7内使用？ (Issue #21)





 
Closed #21 as completed.
