### ISSUE TITLE
预测标签，以及样本不平均的过采样训练方法

### ISSUE THREAD

**Issue by xiaohangguo** [z1069614715/objectdetection_script#22]
魔导，有个问题困扰了很久，我想在coco数据集的基础上加上自己的数据集训练，但是会导致样本标签不平均的问题，能不能出一些权重采样，之类的小trick的视频？另外想问一下如果是预训练模型，比如yolov8s.pt，他已经在coco上训练了，那我在我自定义数据集上训练以后，如何同时也预测之前就学到的标签呢？比如仍然要识别person、bus诸如此类的标签，实验一直没试出来。

预测不出来不知道是不是模型把那些遗忘掉了，还是说需要冻结参数之类的操作，还是因为我配置项的问题，是不是需要修改模型的yaml文件​(好像没成功)

**Comment by z1069614715** [comment]
这好像是要增量学习吧... 不是一个简单的问题
