### ISSUE TITLE
SequentialSelfAttention注意力机制来源论文

### ISSUE THREAD

**Issue by LSJ5106** [z1069614715/objectdetection_script#28]
SequentialSelfAttention注意力机制来源论文似乎不对呢，和上面的Polor……是重复的。请问SequentialSelfAttention来源论文是哪一篇呢？

**Comment by ChenJian7578** [comment]
兄弟有找到吗？

**Comment by LSJ5106** [comment]
没有呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月31日(周三) 下午2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [z1069614715/objectdetection_script] SequentialSelfAttention注意力机制来源论文 (Issue #28)




 
兄弟有找到吗？
