### ISSUE TITLE
大佬您好，请问您有遇到过pow() takes no keyword argumentspow这个问题吗？

### ISSUE THREAD

**Issue by APTX4689** [z1069614715/objectdetection_script#4]
![image](https://user-images.githubusercontent.com/92523008/218245616-5fd33364-96f3-486d-83cf-cbd623f9b4cd.png)

**Comment by z1069614715** [comment]
改成math.pow

**Comment by APTX4689** [comment]
> 改成math.pow

十分感谢！解决了

**Comment by APTX4689** [comment]
> 

删掉"exp="就可以

**Comment by z1069614715** [comment]
删掉exp是不会报错 但是代码的意思就跟之前不对了喔 那个动量的参数就变了 跟论文的意思不一样了喔

**Comment by APTX4689** [comment]
> 删掉exp是不会报错 但是代码的意思就跟之前不对了喔 那个动量的参数就变了 跟论文的意思不一样了喔

![image](https://user-images.githubusercontent.com/92523008/218246984-48f00e2b-2766-4855-acc1-b84b2c8b2dbb.png)
但是我修改为math.pow后运行好像还是不太行，您可以帮忙看看吗

**Comment by z1069614715** [comment]
我知道了，原来你报错是因为python版本小于3.8，我今晚更新一下 你再重新复制

**Comment by APTX4689** [comment]
> 我知道了，原来你报错是因为python版本小于3.8，我今晚更新一下 你再重新复制

太感谢您了

**Comment by APTX4689** [comment]
> > 我知道了，原来你报错是因为python版本小于3.8，我今晚更新一下 你再重新复制
> 
> 太感谢您了

试了一下 确实是可以的，python3.7.12

**Comment by z1069614715** [comment]
重新拉的代码还不可以吗？

**Comment by APTX4689** [comment]
> 重新拉的代码还不可以吗？

已经可以运行了。就是用您昨天晚上更新后的代码，在python3.7.12的环境下

**Comment by z1069614715** [comment]
ok 那就行了 就是之前的代码要3.8以上 现在我改了 3.8之前的都可以用
