### ISSUE TITLE
导现在yolov5-asf里的MAX_pool3d已经改掉了，好像变成nn.functional.max_pool3d，这个了，然后在kernel_size基础上多了个input

### ISSUE THREAD

**Issue by leileilei2000** [z1069614715/objectdetection_script#44]

**Comment by z1069614715** [comment]
都差不多吧

**Comment by leileilei2000** [comment]
> 都差不多吧

导 我直接用MAX_pool3d，会报错max_pool3d_with_indices_backward_cuda does not have a deterministic implementation, but you set，所以找了一下发现换了，然后结构直接全变了

**Comment by leileilei2000** [comment]
> 都差不多吧

导我不管是MAX_pool3d还是max_pool3d，在yolov5都报错了max_pool3d_with_indices_backward_cuda does not have a deterministic implementation, but you set ，

**Comment by z1069614715** [comment]
这个按照他提示设置就行了，跟这些没关系

**Comment by leileilei2000** [comment]
我按照设置运行了，但是就是报错max_pool3d_with_indices_backward_cuda does not have a deterministic implementation, but you set，我找到一种方法是torch.use_deterministic_algorithms(False)，关掉这个决定性算法，但是有人说会非常影响结果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "z1069614715/objectdetection_script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月30日(星期四) 晚上6:23
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [z1069614715/objectdetection_script] 导现在yolov5-asf里的MAX_pool3d已经改掉了，好像变成nn.functional.max_pool3d，这个了，然后在kernel_size基础上多了个input (Issue #44)





 
这个按照他提示设置就行了，跟这些没关系

**Comment by z1069614715** [comment]
没有非常影响结果的说法，解决这问题的唯一方法就是torch.use_deterministic_algorithms(False)，不然就不用这个asf

**Comment by leileilei2000** [comment]
好的导！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月30日(星期四) 晚上6:30
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [z1069614715/objectdetection_script] 导现在yolov5-asf里的MAX_pool3d已经改掉了，好像变成nn.functional.max_pool3d，这个了，然后在kernel_size基础上多了个input (Issue #44)














 
没有非常影响结果的说法，解决这问题的唯一方法就是torch.use_deterministic_algorithms(False)，不然就不用这个asf
