### ISSUE TITLE
yolov7 heat_map出现了一个bug

### ISSUE THREAD

**Issue by ZZM11** [z1069614715/objectdetection_script#5]
我的yolov7模型需要固定图片的大小为512，512，我更改以下代码：
![image](https://user-images.githubusercontent.com/63572595/218700396-0f4dae94-f709-431c-a4b8-4bff9a1fbfb3.png)
图像有上下的黑边，这是一个情况
![image](https://user-images.githubusercontent.com/63572595/218700744-3732a45d-6ecf-4d3e-bde7-c2aeda3912ec.png)

我尝试提前把图片处理好为512*512，再运行代码
只要是512*512的图片就什么输出都没有，进度条为0就终止了，就请问这个yolov7_heatmap有限制图片大小或者该怎么更改这种情况？

**Comment by z1069614715** [comment]
那你上面哪一个图是怎么得出的呢

**Comment by ZZM11** [comment]
上个图是采用letterbox来resize出来的，有黑边
所以我用其他软件处理好图片再运行代码就没有结果

**Comment by ZZM11** [comment]
换句话说我只要输入512*512的图片就没有结果。。
但我的模型是在512*512的大小下训练的

**Comment by z1069614715** [comment]
没有结果是跟你模型预测的置信度和热力图有关系，热力图比较玄学，这个512x512的你需要debug看看具体那一块导致模型出现异常，
